#!/usr/bin/env python3
"""Calibrate per-layer Qwen activation ranges for CKKS approximations."""

from __future__ import annotations

import argparse
import json
import time
from collections import defaultdict
from pathlib import Path

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.models.qwen2.modeling_qwen2 import apply_rotary_pos_emb


QWEN_DIRECTORY = Path(__file__).resolve().parents[1]
DEFAULT_MODEL = QWEN_DIRECTORY / "pretrained_parameters" / "Qwen2.5-0.5B"
DEFAULT_OUTPUT = QWEN_DIRECTORY / "validation_output" / "he_calibration.json"
DEFAULT_CPP_OUTPUT = QWEN_DIRECTORY / "he" / "qwen25_05b_silu_feature_ranges.inc"
CPP_FEATURE_POSITIONS = 8
DEFAULT_TEXTS = [
    "Hello, how are you?",
    "Hello, my name is Qwen.",
    "Explain homomorphic encryption in one sentence.",
    "The quick brown fox jumps over the lazy dog.",
    "Write a short C++ function that adds two integers.",
    "Machine learning systems should be tested against references.",
    "What is the capital of France?",
    "A transformer decoder predicts the next token.",
    "Privacy preserving inference keeps user inputs confidential.",
]


def tensor_stats(values: list[torch.Tensor]) -> dict[str, float | int]:
    flattened = torch.cat([value.detach().cpu().to(torch.float64).flatten() for value in values])
    quantiles = torch.quantile(
        flattened,
        torch.tensor([0.001, 0.01, 0.5, 0.99, 0.999], dtype=torch.float64),
    )
    return {
        "count": flattened.numel(),
        "min": flattened.min().item(),
        "p0_1": quantiles[0].item(),
        "p1": quantiles[1].item(),
        "p50": quantiles[2].item(),
        "p99": quantiles[3].item(),
        "p99_9": quantiles[4].item(),
        "max": flattened.max().item(),
    }


def feature_ranges(values: list[torch.Tensor]) -> dict[str, list[float]]:
    rows = torch.cat(
        [value.detach().cpu().to(torch.float64).reshape(-1, value.shape[-1])
         for value in values],
        dim=0,
    )
    return {
        "minimum": rows.amin(dim=0).tolist(),
        "maximum": rows.amax(dim=0).tolist(),
    }


def cpp_float(value: float) -> str:
    text = f"{value:.9g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "f"


def write_cpp_feature_ranges(
    path: Path,
    aggregate: dict[str, dict[str, list[float]]],
    positions: dict[str, dict[str, dict[str, list[float]]]],
) -> None:
    lines = [
        "// Generated by tools/calibrate_he_approximations.py.",
        "constexpr std::array<std::array<FeatureRange, 4864>, 24>",
        "    silu_feature_ranges{{",
    ]
    for layer in range(24):
        name = f"layer_{layer}.mlp_gate"
        overall = aggregate[name]
        calibrated_positions = positions[name]
        if len(overall["minimum"]) != 4864:
            raise RuntimeError(f"unexpected MLP width for {name}")
        lines.append("        {{")
        for feature in range(4864):
            intervals = []
            for position in range(CPP_FEATURE_POSITIONS):
                stats = calibrated_positions[str(position)]
                intervals.append(
                    "{" + ", ".join([
                        cpp_float(stats["minimum"][feature]),
                        cpp_float(stats["maximum"][feature]),
                    ]) + "}"
                )
            lines.append(
                "            {" + ", ".join([
                    cpp_float(overall["minimum"][feature]),
                    cpp_float(overall["maximum"][feature]),
                    "{{" + ", ".join(intervals) + "}}",
                ]) + "},"
            )
        lines.append("        }},")
    lines.extend(["    }};", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--cpp-output", type=Path, default=DEFAULT_CPP_OUTPUT)
    parser.add_argument("--threads", type=int, default=16)
    parser.add_argument("--max-length", type=int, default=128)
    args = parser.parse_args()

    if not args.model.is_dir():
        parser.error(f"model directory does not exist: {args.model}")
    if args.threads <= 0:
        parser.error("--threads must be positive")
    if args.max_length <= 0:
        parser.error("--max-length must be positive")

    torch.set_num_threads(args.threads)
    started = time.perf_counter()
    tokenizer = AutoTokenizer.from_pretrained(args.model, local_files_only=True)
    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        local_files_only=True,
        dtype=torch.float64,
        attn_implementation="eager",
    )
    model.eval()

    samples: dict[str, list[torch.Tensor]] = defaultdict(list)
    position_samples: dict[
        str, dict[int, list[torch.Tensor]]
    ] = defaultdict(lambda: defaultdict(list))
    feature_samples: dict[str, list[torch.Tensor]] = defaultdict(list)
    position_feature_samples: dict[
        str, dict[int, list[torch.Tensor]]
    ] = defaultdict(lambda: defaultdict(list))
    hooks = []

    def register_rms_input(name: str, module: torch.nn.Module, epsilon: float) -> None:
        def capture(_module: torch.nn.Module, inputs: tuple[torch.Tensor, ...]) -> None:
            hidden = inputs[0].detach()
            variance = hidden.square().mean(dim=-1) + epsilon
            samples[name].append(variance)
            for position in range(variance.shape[1]):
                position_samples[name][position].append(
                    variance[:, position]
                )

        hooks.append(module.register_forward_pre_hook(capture))

    def register_output(name: str, module: torch.nn.Module) -> None:
        def capture(
            _module: torch.nn.Module,
            _inputs: tuple[torch.Tensor, ...],
            output: torch.Tensor,
        ) -> None:
            detached = output.detach()
            samples[name].append(detached)
            feature_samples[name].append(detached)
            for position in range(detached.shape[1]):
                position_feature_samples[name][position].append(
                    detached[:, position, :]
                )
            for position in range(detached.shape[1]):
                position_samples[name][position].append(
                    detached[:, position]
                )

        hooks.append(module.register_forward_hook(capture))

    def register_attention_scores(
        layer_index: int, layer: torch.nn.Module
    ) -> None:
        attention = layer.self_attn

        def capture(
            _module: torch.nn.Module,
            inputs: tuple[torch.Tensor, ...],
            kwargs: dict[str, object],
        ) -> None:
            hidden_value = (
                inputs[0] if inputs else kwargs.get("hidden_states")
            )
            if not isinstance(hidden_value, torch.Tensor):
                raise RuntimeError(
                    "attention calibration hook did not receive hidden_states"
                )
            hidden = hidden_value.detach()
            batch, tokens, _ = hidden.shape
            position_ids = torch.arange(
                tokens, device=hidden.device, dtype=torch.long
            ).unsqueeze(0).expand(batch, -1)
            query = attention.q_proj(hidden).view(
                batch, tokens, attention.config.num_attention_heads, attention.head_dim
            ).transpose(1, 2)
            key = attention.k_proj(hidden).view(
                batch,
                tokens,
                attention.config.num_key_value_heads,
                attention.head_dim,
            ).transpose(1, 2)
            cosine, sine = model.model.rotary_emb(hidden, position_ids)
            query, key = apply_rotary_pos_emb(
                query, key, cosine, sine
            )
            group_size = (
                attention.config.num_attention_heads
                // attention.config.num_key_value_heads
            )
            repeated_key = key.repeat_interleave(group_size, dim=1)
            scores = torch.matmul(
                query, repeated_key.transpose(-1, -2)
            ) * attention.scaling
            causal = torch.ones(
                tokens, tokens, dtype=torch.bool, device=hidden.device
            ).tril()
            valid_scores = scores.masked_select(
                causal[None, None, :, :]
            )
            samples[
                f"layer_{layer_index}.attention_score"
            ].append(valid_scores)
            for query_token in range(tokens):
                position_samples[
                    f"layer_{layer_index}.attention_score"
                ][query_token].append(
                    scores[:, :, query_token, : query_token + 1]
                )

            row_maximum = scores.masked_fill(
                ~causal[None, None, :, :], -torch.inf
            ).max(dim=-1, keepdim=True).values
            shifted = (scores - row_maximum).masked_select(
                causal[None, None, :, :]
            )
            samples[
                f"layer_{layer_index}.attention_shifted_score"
            ].append(shifted)
            for query_token in range(tokens):
                position_samples[
                    f"layer_{layer_index}.attention_shifted_score"
                ][query_token].append(
                    (
                        scores[
                            :, :, query_token, : query_token + 1
                        ]
                        - row_maximum[:, :, query_token]
                    )
                )

            if tokens > 1:
                for query_token in range(1, tokens):
                    visible = scores[:, :, query_token, : query_token + 1]
                    top_two = torch.topk(
                        visible, k=2, dim=-1
                    ).values
                    samples[
                        f"layer_{layer_index}.attention_top_gap"
                    ].append(top_two[..., 0] - top_two[..., 1])
                    position_samples[
                        f"layer_{layer_index}.attention_top_gap"
                    ][query_token].append(
                        top_two[..., 0] - top_two[..., 1]
                    )

        hooks.append(
            attention.register_forward_pre_hook(
                capture, with_kwargs=True
            )
        )

    epsilon = float(model.config.rms_norm_eps)
    for layer_index, layer in enumerate(model.model.layers):
        register_attention_scores(layer_index, layer)
        register_rms_input(
            f"layer_{layer_index}.input_rms_variance",
            layer.input_layernorm,
            epsilon,
        )
        register_rms_input(
            f"layer_{layer_index}.post_attention_rms_variance",
            layer.post_attention_layernorm,
            epsilon,
        )
        register_output(
            f"layer_{layer_index}.mlp_gate",
            layer.mlp.gate_proj,
        )
    register_rms_input("final_rms_variance", model.model.norm, epsilon)

    with torch.no_grad():
        for text in DEFAULT_TEXTS:
            encoded = tokenizer(
                text,
                return_tensors="pt",
                truncation=True,
                max_length=args.max_length,
            )
            model(**encoded, use_cache=False, return_dict=True)

    for hook in hooks:
        hook.remove()

    statistics = {name: tensor_stats(values) for name, values in sorted(samples.items())}
    position_statistics = {
        name: {
            str(position): tensor_stats(values)
            for position, values in sorted(positions.items())
        }
        for name, positions in sorted(position_samples.items())
    }
    feature_statistics = {
        name: feature_ranges(values)
        for name, values in sorted(feature_samples.items())
    }
    position_feature_statistics = {
        name: {
            str(position): feature_ranges(values)
            for position, values in sorted(position_values.items())
        }
        for name, position_values in sorted(position_feature_samples.items())
    }
    output = {
        "model": str(args.model.resolve()),
        "dtype": "float64",
        "rms_norm_epsilon": epsilon,
        "texts": DEFAULT_TEXTS,
        "elapsed_seconds": time.perf_counter() - started,
        "statistics": statistics,
        "position_statistics": position_statistics,
        "feature_calibration": {
            "features": 4864,
            "positions": CPP_FEATURE_POSITIONS,
            "margin_is_applied_by_cpp": True,
        },
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    write_cpp_feature_ranges(
        args.cpp_output, feature_statistics,
        position_feature_statistics,
    )

    print(f"model: {args.model}")
    print(f"samples: {len(DEFAULT_TEXTS)}")
    print(f"output: {args.output}")
    print(f"C++ feature ranges: {args.cpp_output}")
    print("node                                      min          p0.1         p99.9        max")
    for name, stats in statistics.items():
        print(
            f"{name:<41} {stats['min']:<12.5e} {stats['p0_1']:<12.5e} "
            f"{stats['p99_9']:<12.5e} {stats['max']:<12.5e}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
