set(USE_HARDWARE OFF)
if(USE_HARDWARE)
    add_definitions(-DPIR_USE_HARDWARE)
    message(STATUS "pir hardware version")
else()
    message(STATUS "pir software version")
endif()

file(GLOB PIR_BGV_SOURCE_FILES "*.cpp" "*.c")
add_executable(pir_bgv ${PIR_BGV_SOURCE_FILES})
target_link_libraries(pir_bgv PUBLIC poseidon_shared)
message(STATUS "PIR build success")